version: '3.8'

services:
  webapp:
    build: ./app
    container_name: football_app
    ports:
      - "8501:8501"
    depends_on:
      - mongo
    environment:
      - CHROME_BIN=/usr/bin/chromium
      - CHROMEDRIVER_PATH=/usr/bin/chromedriver

  mongo:
    image: mongo:latest
    container_name: pokedex_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: